package hl7.segments;

public class Pv1Segment extends Hl7segment {
    //listing all fields in PV1
    private String SetIdPatVisit;
    private String PatClass;
    private String AssignedPatLocation;
    private String AdmissionType;
    private String PreadmitNumber;
    private String PriorPatLocation;
    private String AttendingDoc;
    private String ReferringDoc;
    private String ConsultingDoc;
    private String HospitalService;
    private String TempLocation;
    private String PreadmitTestIndicator;
    private String ReadmissionIndicator;
    private String AdmitSource;
    private String AmbulatoryStatus;
    private String VipIndicator;
    private String AdmittingDoc;
    private String PatType;
    private String VisitNum;
    private String FinancialClass;
    private String ChargePriceIndicator;
    private String CourtesyCode;
    private String CreditRating;
    private String ContractCode;
    private String ContractEffectiveDate;
    private String ContractAmount;
    private String ContractPeriod;
    private String interestCode;
    private String TransferToBadDebtCode;
    private String TransferToBadDebtDate;
    private String DischargeDisposition;
    private String DischargedToLocation;
    private String DietType;
    private String ServicingFac;
    private String BedStatus;
    private String AccountStatus;
    private String PendingLocation;
    private String PriorTemporaryLocation;
    private String AdmitDateTime;
    private String DischargeDateTime;
    private String CurrentPatBalance;
    private String TotalCharges;
    private String TotalAdjustments;
    private String TotalPayments;
    private String AlternateVisitId;
    private String VisitIndicator;
    private String OtherHealthcareProvider;

    public Pv1Segment(String[] fields) {
        this.SetIdPatVisit = get(fields, 1);
        this.PatClass = get(fields, 2);
        this.AssignedPatLocation = get(fields, 3);
        this.AdmissionType = get(fields, 4);
        this.PreadmitNumber = get(fields, 5);
        this.PriorPatLocation = get(fields, 6);
        this.AttendingDoc = get(fields, 7);
        this.ReferringDoc = get(fields, 8);
        this.ConsultingDoc = get(fields, 9);
        this.HospitalService = get(fields, 10);
        this.TempLocation = get(fields, 11);
        this.PreadmitTestIndicator = get(fields, 12);
        this.ReadmissionIndicator = get(fields, 13);
        this.AdmitSource = get(fields, 14);
        this.AmbulatoryStatus = get(fields, 15);
        this.VipIndicator = get(fields, 16);
        this.AdmittingDoc = get(fields, 17);
        this.PatType = get(fields, 18);
        this.VisitNum = get(fields, 19);
        this.FinancialClass = get(fields, 20);
        this.ChargePriceIndicator = get(fields, 21);
        this.CourtesyCode = get(fields, 22);
        this.CreditRating = get(fields, 23);
        this.ContractCode = get(fields, 24);
        this.ContractEffectiveDate = get(fields, 25);
        this.ContractAmount = get(fields, 26);
        this.ContractPeriod = get(fields, 27);
        this.interestCode = get(fields, 28);
        this.TransferToBadDebtCode = get(fields, 29);
        this.TransferToBadDebtDate = get(fields, 30);
        this.DischargeDisposition = get(fields, 31);
        this.DischargedToLocation = get(fields, 32);
        this.DietType = get(fields, 33);
        this.ServicingFac = get(fields, 34);
        this.BedStatus = get(fields, 35);
        this.AccountStatus = get(fields, 36);
        this.PendingLocation = get(fields, 37);
        this.PriorTemporaryLocation = get(fields, 38);
        this.AdmitDateTime = get(fields, 39);
        this.DischargeDateTime = get(fields, 40);
        this.CurrentPatBalance = get(fields, 41);
        this.TotalCharges = get(fields, 42);
        this.TotalAdjustments = get(fields, 43);
        this.TotalPayments = get(fields, 44);
        this.AlternateVisitId = get(fields, 45);
        this.VisitIndicator = get(fields, 46);
        this.OtherHealthcareProvider = get(fields, 47);
    }

}
